#!/usr/bin/env zsh

function makelink {
    local prev
    local dst

    prev="$(pwd)"
    [[ -n "$2" ]] && dst="$2" || dst="$HOME"
    cd "$dst" || exit 1

    echo -e "Linking $1 to $dst"
    if [[ -d "$1" ]]; then
        /bin/ln -sF "$1"
    elif [[ -f "$1" ]]; then
        /bin/ln -sf "$1"
    else
        echo -e "Could not find '$1', not linking!"
    fi
    cd "$prev"
}

function setup_vim {
    makelink ~/workspace/dotfiles/.vim
    makelink ~/workspace/dotfiles/.vimrc
    # makelink ~/workspace/dotfiles/.xvimrc

    makelink ~/Library/Mobile\ Documents/com~apple~CloudDocs/Vim/pack ~/.vim
    makelink ~/Library/Mobile\ Documents/com~apple~CloudDocs/Vim/spell ~/.vim

    mkdir -p ~/.vim/backup/undo
}

function setup_shell_tools {
    cd "$HOME" || exit 1

    # makelink ~/workspace/dotfiles/.zsh
    makelink ~/workspace/dotfiles/.zshrc
    makelink ~/workspace/dotfiles/.zshenv

    # makelink ~/workspace/dotfiles/.ipython
    # makelink ~/workspace/dotfiles/.bin
}

function setup_git {
    makelink ~/workspace/dotfiles/.tigrc
    makelink ~/workspace/dotfiles/.git_template
    makelink ~/workspace/dotfiles/.gitignore
    makelink ~/workspace/dotfiles/.gitconfig
}

echo -e "Bootstrapping..."
setup_vim
setup_shell_tools
# setup_git
echo -e "Done!"
